server:
  port: 5000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/user/**

        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/project/**

        - id: issue-service
          uri: lb://ISSUE-SERVICE
          predicates:
            - Path=/api/v1/issue/**

        - id: invitation-service
          uri: lb://INVITATION-SERVICE
          predicates:
            - Path=/api/v1/invite/**

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comment/**

#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.web: DEBUG
#    reactor.netty: DEBUG
#    org.springframework.http.server.reactive: DEBUG
