spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**,/api/user/**

        - id: project-service
          uri: lb:http://PROJECT-SERVICE
          predicates:
            - Path=/api/v1/project/**

        - id: issue-service
          uri: lb:http://ISSUE-SERVICE
          predicates:
            - Path=/api/v1/issue/**

        - id: invite-service
          uri: lb:http://INVITE-SERVICE
          predicates:
            - Path=/api/v1/invite/**

        - id: comment-service
          uri: lb:http://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comment/**
