spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invitation_db
    username: postgres
    password: roczyno
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: adiabajacob9@gmail.com
    password: yxysexiqozqnyrke
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    mailing:
      frontend:
        activation-url: http://localhost:500

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: invitationConfirmation:com.roczyno.invitationservice.kafka.InvitationConfirmation
