spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/issue_db
    username: postgres
    password: roczyno
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: issueConfirmation:com.roczyno.issueservice.kafka.IssueConfirmation
