spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sub_db
    username: postgres
    password: roczyno
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
