spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: roczyno
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false
    schemas: public
    clean-disabled: true
    user: postgres
    password: roczyno

