services:
  postgres:
    container_name: pm_pq_sql
    image: postgres
    environment:
      POSTGRES_USER: roczyno
      POSTGRES_PASSWORD: roczyno
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 1234:5432
    networks:
      - pm_microservice_net
    restart: unless-stopped

  redis:
    container_name: pm_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - pm_microservice_net
    restart: unless-stopped
    volumes:
      - redis:/data

  mongoDB:
    container_name: pm_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: roczyno
      MONGO_INITDB_ROOT_PASSWORD: roczyno
    networks:
      - pm_microservice_net

  mongo_express:
    container_name: pm_mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB
      ME_CONFIG_MONGODB_ADMINUSERNAME: roczyno
      ME_CONFIG_MONGODB_ADMINPASSWORD: roczyno
    networks:
      - pm_microservice_net

  mail_dev:
    container_name: pm_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - pm_microservice_net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: pm_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - pm_microservice_net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: pm-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - pm_microservice_net

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - pm_microservice_net

  config-server:
    container_name: config-server
    build:
      context: ./services/config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - pm_microservice_net
    restart: unless-stopped

  discovery-service:
    container_name: discovery-service
    build:
      context: ./services/discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  gateway-service:
    container_name: gateway-service
    build:
      context: ./services/gateway-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - config-server
      - discovery-service
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  user-service:
    container_name: user-service
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery-service
      - postgres
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user_db

  project-service:
    container_name: project-service
    build:
      context: ./services/project-service
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery-service
      - postgres
      - user-service
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/project_db

  issue-service:
    container_name: issue-service
    build:
      context: ./services/issue-service
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery-service
      - postgres
      - project-service
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/issue_db

  comment-service:
    container_name: comment-service
    build:
      context: ./services/comment-service
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery-service
      - postgres
      - issue-service
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/comment_db

  invitation-service:
    container_name: invitation-service
    build:
      context: ./services/invitation-service
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery-service
      - postgres
      - project-service
      - user-service
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/invitation_db

  chat-service:
    container_name: chat-service
    build:
      context: ./services/chat-service
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery-service
      - postgres
      - user-service
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chat_db

  notification-service:
    container_name: notification-service
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery-service
      - kafka
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  subscription-service:
    container_name: subscription-service
    build:
      context: ./services/subscription-service
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - discovery-service
      - postgres
      - user-service
    networks:
      - pm_microservice_net
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/subscription_db

networks:
  pm_microservice_net:
    driver: bridge

volumes:
  postgres:
  mongo:
  redis:
