CREATE TABLE _user
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(255),
    email          VARCHAR(255),
    password       VARCHAR(255),
    project_size   INTEGER                                  NOT NULL,
    enabled        BOOLEAN,
    account_locked BOOLEAN,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk__user PRIMARY KEY (id)
);

CREATE TABLE role
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

ALTER TABLE role
    ADD CONSTRAINT uc_role_name UNIQUE (name);


CREATE TABLE _user_roles
(
    roles_id INTEGER NOT NULL,
    users_id INTEGER NOT NULL
);

ALTER TABLE _user
    ADD CONSTRAINT uc__user_email UNIQUE (email);

ALTER TABLE _user
    ADD CONSTRAINT uc__user_username UNIQUE (username);

ALTER TABLE _user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (roles_id) REFERENCES role (id);

ALTER TABLE _user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (users_id) REFERENCES _user (id);
