CREATE TABLE token
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token        VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    expired_at   TIMESTAMP WITHOUT TIME ZONE,
    validated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id      INTEGER                                  NOT NULL,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_USERID FOREIGN KEY (user_id) REFERENCES _user (id);
