spring:
  application:
    name: project-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8080

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true



#Resilience4J
resilience4j:
  circuitbreaker:
    instances:
      userBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based

      chatBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based
  retry:
    instances:
      chatBreaker:
        max-attempts: 5
        wait-duration: 10s

  ratelimiter:
    instances:
      chatBreaker:
        timeout-duration: 0
        limit-refresh-period: 4
        limit-for-period: 2




